name: scraper-linkedin
channels:
  - defaults
  - conda-forge
dependencies:
  - beautifulsoup4=4.12.2
  - blas=1.0
  - bottleneck=1.3.5
  - brotli-python=1.0.9
  - bs4=4.12.2
  - bzip2=1.0.8
  - ca-certificates=2023.12.12
  - expat=2.5.0
  - libcxx=14.0.6
  - libffi=3.4.4
  - libgfortran=5.0.0
  - libgfortran5=11.3.0
  - libopenblas=0.3.21
  - llvm-openmp=14.0.6
  - ncurses=6.4
  - numexpr=2.8.7
  - numpy=1.26.4
  - numpy-base=1.26.4
  - openssl=3.0.13
  - pandas=2.1.4
  - pip=23.3.1
  - pysocks=1.7.1
  - python=3.12.2
  - python-dateutil=2.8.2
  - python-tzdata=2023.3
  - pytz=2023.3.post1
  - pyyaml=6.0.1
  - readline=8.2
  - setuptools=68.2.2
  - six=1.16.0
  - soupsieve=2.5
  - sqlite=3.41.2
  - tk=8.6.12
  - tqdm=4.65.0
  - tzdata=2023d
  - wheel=0.41.2
  - xz=5.4.6
  - yaml=0.2.5
  - zlib=1.2.13
  - pip:
      - attrs==23.2.0
      - certifi==2024.2.2
      - charset-normalizer==3.3.2
      - chromedriver-autoinstaller==0.6.4
      - chromedriver-binary==123.0.6312.10.0
      - debugpy==1.8.1
      - h11==0.14.0
      - idna==3.6
      - jaraco-classes==3.4.0
      - jaraco-context==6.0.1
      - jaraco-functools==4.1.0
      - keyring==25.6.0
      - more-itertools==10.5.0
      - outcome==1.3.0.post0
      - packaging==23.2
      - python-dotenv==1.0.1
      - requests==2.31.0
      - selenium==4.18.1
      - sniffio==1.3.0
      - sortedcontainers==2.4.0
      - trio==0.24.0
      - trio-websocket==0.11.1
      - typing-extensions==4.9.0
      - urllib3==1.26.16
      - webdriver-manager==4.0.2
      - wsproto==1.2.0
