log_file: "logfile.txt"             # logs/

sample_search: "sample_search.html" # data/

results:
  posts_file: './results/posts.csv'
  test_posts_file: './results/test.csv'
  easy_apply_file: './results/easy_apply.csv'
  